# numpy module

numpy module is one of the most important module in python for scientific computing. It is the foundation on which many other popular modules run. pandas uses numpy in the background.

Since numpy uses c code in the background, it is extremely fast compared to python.

In [1]:
import numpy as np

In [2]:
my_array = np.array([1,4,5,6])

In [3]:
my_array

array([1, 4, 5, 6])

In [4]:
type(my_array)

numpy.ndarray

numpy stores data in it's own format (objects).

# Operations with numpy.ndarrays

Working with numpy arrays in most parts do not require you to use loops.

In [5]:
my_array * 100

array([100, 400, 500, 600])

In [6]:
my_array**2

array([ 1, 16, 25, 36])

In [7]:
np.sin(my_array)

array([ 0.84147098, -0.7568025 , -0.95892427, -0.2794155 ])

In [8]:
my_array + 10

array([11, 14, 15, 16])

# Creating and modifying arrays

In [9]:
my_array = np.arange(100)

In [10]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
reshaped_array = my_array.reshape(10,10)

In [16]:
reshaped_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [17]:
reshaped_array.T

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [18]:
reshaped_array.diagonal()

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

# Indexing and filtering

## Indexing

In [22]:
reshaped_array[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
reshaped_array[::2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [27]:
reshaped_array[:,::3]

array([[ 0,  3,  6,  9],
       [10, 13, 16, 19],
       [20, 23, 26, 29],
       [30, 33, 36, 39],
       [40, 43, 46, 49],
       [50, 53, 56, 59],
       [60, 63, 66, 69],
       [70, 73, 76, 79],
       [80, 83, 86, 89],
       [90, 93, 96, 99]])

## Filtering

Doing a boolean operation with a numpy array will return a similar dimension array filled with True or False.

In [28]:
reshaped_array % 2 == 0

array([[ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False]], dtype=bool)

If we pass this boolean array to the original array as index, it will return only those elements where the value is True. But as a single dimension array.

In [30]:
boolean_array = reshaped_array % 2 == 0
reshaped_array[boolean_array]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

# Operations on arrays

In [39]:
np.linalg.eigvals(reshaped_array)

array([  5.11140380e+02 +0.00000000e+00j,
        -1.61403801e+01 +0.00000000e+00j,
        -1.08240541e-15 +1.13487571e-14j,
        -1.08240541e-15 -1.13487571e-14j,
        -2.19369865e-15 +5.68829454e-15j,
        -2.19369865e-15 -5.68829454e-15j,
         7.68565730e-17 +1.22384946e-15j,
         7.68565730e-17 -1.22384946e-15j,
        -3.95025520e-16 +0.00000000e+00j,  -2.10164363e-16 +0.00000000e+00j])

# Exercise

Create a matrix of random integers of 5x5 size, filter the odd numbers and find the max of those numbers.

clue:
```python
np.random.randint(100, size=(5,5))
```